clients:
  sbom:
      service_url: https://sbom-request.canonical.com
      department: charm_engineering
      email: tony.meyer@canonical.com
      team: charm_tech
  secscan: {}


artifacts:
  - name: 'jubilant'
    type: 'sdist'
    compression: 'gz'
    ssdlc_params:
        name: 'jubilant'
        version: ''
        channel: 'stable'
        cycle: '25.10'
