name: Publish

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-pypi

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false

      - name: Build dist packages
        run: uv build

      - name: Attest build provenance
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373  # v4.1.1
        with:
          subject-path: 'dist/*'

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1

  secscan:
    uses: ./.github/workflows/sbom-secscan.yaml
